#define VERSION_MAJOR    0
#define VERSION_MINOR    0
#define VERSION_BUILD    1
#define VERSION_REVISION 0

#define _STR(X) #X
#define STR(X) _STR(X)

#define MAKE_VERSION_STR(A, B, C, D) STR(A) "." STR(B) "." STR(C) "." STR(D)

#define VERSION_STR MAKE_VERSION_STR(VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD, VERSION_REVISION)
